version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20     # âœ… Node 20ìœ¼ë¡œ ëª…ì‹œ (Firebase + Vite ìš”êµ¬ì‚¬í•­)
    commands:
      - echo "Installing dependencies..."
      - cd SW-1.201/frontend
      - npm ci || npm install
      - chmod -R 755 node_modules/.bin || true   # âœ… ì‹¤í–‰ê¶Œí•œ ë¶€ì—¬ (Vite í¬í•¨)

  build:
    commands:
      - echo "ðŸš€ Building React (Vite) app..."
       - echo "VITE_API_BASE_URL=http://capstone-front-back-nlb-5df2d37f3e3da2a2.elb.ap-northeast-2.amazonaws.com:5000" > .env
      - npm run build

artifacts:
  base-directory: SW-1.201/frontend/dist
  files:
    - '**/*'
