version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: frontend/scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: frontend/scripts/after_install.sh
      timeout: 600
      runas: ec2-user
    - location: frontend/scripts/fix_permissions.sh     # ✅ 추가
      timeout: 60
      runas: root                                       # ✅ root 권한으로 소유권 복구

  ApplicationStart:
    - location: frontend/scripts/start_all.sh
      timeout: 600
      runas: ec2-user

  ApplicationStop:
    - location: frontend/scripts/stop_all.sh
      timeout: 300
      runas: ec2-user
