version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app/backend
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/backend
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/clean_old_files.sh
      timeout: 120
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/fix_permissions.sh    # ✅ 추가
      timeout: 60
      runas: root                            # ✅ chown은 root 권한 필요

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
