version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing backend dependencies..."
      - cd panel1.0/backend
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "No build step required for Flask backend."
  post_build:
    commands:
      - echo "Backend build completed successfully."

artifacts:
  base-directory: panel1.0/backend
  files:
    - appspec.yml
    - scripts/**/*
    - main.py
    - requirements.txt
    - app/**/*

# artifacts:
#   base-directory: SW-1.201/backend
#   files:
#     - appspec.yml
#     - scripts/**/*
#     - main.py
#     - requirements.txt
